package eu.metatools.up.lang

/**
 * Continues a sequence of [U] by a sequence generated by [block] of type [V]. Their common type [T] is used as the
 * type of result elements.
 */
fun <T : Any, U : T, V : T> Sequence<U>.continuedBy(block: () -> V?) =
    this + generateSequence(block)